import type { Customer } from './types';

export const mockCustomers: Customer[] = [
    {
        id: 1,
        customerId: 'BF2524830024',
        firstName: 'Ивана',
        lastName: 'Иванова',
        email: 'ivana@email.com',
        emailVerified: true,
        phone: '+7 999 123-45-67',
        birthDate: '1990-05-15',
        gender: 'female',
        deliveryAddress: 'г. Москва, ул. Примерная, д. 1, кв. 1',
        registrationDate: '2024-01-01',
        ordersCount: 20,
        totalPurchaseAmount: 99000,
        bonusPoints: 1000,
        status: 'active',
        hasNewsletterSubscription: true,
        hasSecretBoxSubscription: true,
        bonusTransactions: [
            {
                id: 1,
                date: '2024-01-15',
                type: 'accrual',
                amount: 500,
                reason: 'Покупка на 10000₽',
                balanceAfter: 500,
            },
            {
                id: 2,
                date: '2024-01-20',
                type: 'accrual',
                amount: 300,
                reason: 'Покупка на 6000₽',
                balanceAfter: 800,
            },
            {
                id: 3,
                date: '2024-02-01',
                type: 'debit',
                amount: -200,
                reason: 'Списание при покупке',
                balanceAfter: 600,
            },
        ],
        orders: [
            {
                id: 1,
                orderNumber: 'BF2524830024',
                date: '2024-01-15',
                amount: 10000,
                status: 'delivered',
            },
            {
                id: 2,
                orderNumber: 'BF2524830025',
                date: '2024-01-20',
                amount: 6000,
                status: 'delivered',
            },
        ],
    },
    {
        id: 2,
        customerId: 'BF2524830025',
        firstName: 'Мария',
        lastName: 'Петрова',
        email: 'maria@email.com',
        emailVerified: true,
        phone: '+7 999 987-65-43',
        registrationDate: '2024-01-05',
        ordersCount: 15,
        totalPurchaseAmount: 75000,
        bonusPoints: 750,
        status: 'active',
        hasNewsletterSubscription: true,
        hasSecretBoxSubscription: false,
        bonusTransactions: [],
        orders: [],
    },
    {
        id: 3,
        customerId: 'BF2524830026',
        firstName: 'Анна',
        lastName: 'Сидорова',
        email: 'anna@email.com',
        emailVerified: false,
        phone: '+7 999 111-22-33',
        registrationDate: '2024-01-10',
        ordersCount: 5,
        totalPurchaseAmount: 25000,
        bonusPoints: 250,
        status: 'active',
        hasNewsletterSubscription: false,
        hasSecretBoxSubscription: false,
        bonusTransactions: [],
        orders: [],
    },
    {
        id: 4,
        customerId: 'BF2524830027',
        firstName: 'Елена',
        lastName: 'Козлова',
        email: 'elena@email.com',
        emailVerified: true,
        phone: '+7 999 444-55-66',
        registrationDate: '2024-02-01',
        ordersCount: 3,
        totalPurchaseAmount: 15000,
        bonusPoints: 150,
        status: 'inactive',
        hasNewsletterSubscription: false,
        hasSecretBoxSubscription: false,
        bonusTransactions: [],
        orders: [],
    },
];
