import type { Product } from './types';

export const mockProducts: Product[] = [
    {
        id: 1,
        name: 'Стринги на тонких лямках',
        articleNumber: 'BF2524830024',
        slug: 'stringi-na-tonkih-lyamkah',
        description: 'Элегантные стринги из нежного кружева',
        categoryId: 1,
        categoryName: 'Трусы',
        productType: 'panties',
        basePrice: 990,
        promoPrice: 690,
        stockQuantity: 124,
        status: 'active',
        mainImageUrl: 'https://placehold.co/80x80/f5f5f5/333?text=1',
        variants: [],
        createdAt: '2024-01-15',
        updatedAt: '2024-01-20',
    },
    {
        id: 2,
        name: 'Бюстгальтер с пуш-ап',
        articleNumber: 'BF2524830025',
        slug: 'bustgalter-s-push-up',
        description: 'Комфортный бюстгальтер с эффектом пуш-ап',
        categoryId: 2,
        categoryName: 'Бюстгальтеры',
        productType: 'bustier',
        basePrice: 2490,
        promoPrice: 1990,
        stockQuantity: 56,
        status: 'active',
        mainImageUrl: 'https://placehold.co/80x80/f5f5f5/333?text=2',
        variants: [],
        createdAt: '2024-01-10',
        updatedAt: '2024-01-18',
    },
    {
        id: 3,
        name: 'Боди кружевное',
        articleNumber: 'BF2524830026',
        slug: 'body-kruzhevnoe',
        description: 'Изящное кружевное боди',
        categoryId: 3,
        categoryName: 'Боди',
        productType: 'body',
        basePrice: 3990,
        stockQuantity: 0,
        status: 'out_of_stock',
        mainImageUrl: 'https://placehold.co/80x80/f5f5f5/333?text=3',
        variants: [],
        createdAt: '2024-01-05',
        updatedAt: '2024-01-12',
    },
    {
        id: 4,
        name: 'Комплект "Нежность"',
        articleNumber: 'BF2524830027',
        slug: 'komplekt-nezhnost',
        description: 'Комплект из бюстгальтера и трусиков',
        categoryId: 4,
        categoryName: 'Комплекты',
        productType: 'set',
        basePrice: 4990,
        promoPrice: 3990,
        stockQuantity: 34,
        status: 'active',
        mainImageUrl: 'https://placehold.co/80x80/f5f5f5/333?text=4',
        variants: [],
        createdAt: '2024-01-08',
        updatedAt: '2024-01-15',
    },
    {
        id: 5,
        name: 'Стринги шелковые',
        articleNumber: 'BF2524830028',
        slug: 'stringi-shelkovye',
        description: 'Шелковые стринги премиум класса',
        categoryId: 1,
        categoryName: 'Трусы',
        productType: 'panties',
        basePrice: 1490,
        stockQuantity: 89,
        status: 'inactive',
        mainImageUrl: 'https://placehold.co/80x80/f5f5f5/333?text=5',
        variants: [],
        createdAt: '2024-01-03',
        updatedAt: '2024-01-10',
    },
];

export const mockCategories = [
    { id: 1, name: 'Трусы' },
    { id: 2, name: 'Бюстгальтеры' },
    { id: 3, name: 'Боди' },
    { id: 4, name: 'Комплекты' },
];

export const mockCollections = [
    { id: 1, name: 'Весна 2024' },
    { id: 2, name: 'Классика' },
    { id: 3, name: 'Романтика' },
];
