import type { Order } from './types';

export const mockOrders: Order[] = [
    {
        id: 1,
        orderNumber: 'BF2524830024',
        customerId: 1,
        customerName: 'Ивана Иванова',
        customerPhone: '+7 999 123-45-67',
        customerEmail: 'ivana@email.com',
        status: 'new',
        paymentMethod: 'card',
        paymentStatus: 'paid',
        paymentTransactionId: 'TXN123456',
        deliveryMethod: 'courier',
        deliveryAddress: 'г. Москва, ул. Примерная, д. 1, кв. 1',
        deliveryCost: 0,
        itemsTotal: 990,
        totalAmount: 990,
        items: [
            {
                id: 1,
                productId: 1,
                productName: 'Стринги на тонких лямках',
                articleNumber: 'BF2524830024',
                imageUrl: 'https://placehold.co/80x80/f5f5f5/333?text=1',
                price: 990,
                quantity: 1,
                totalPrice: 990,
            },
        ],
        createdAt: '2026-01-01',
        updatedAt: '2026-01-01',
    },
    {
        id: 2,
        orderNumber: 'BF2524830025',
        customerId: 2,
        customerName: 'Мария Петрова',
        customerPhone: '+7 999 987-65-43',
        customerEmail: 'maria@email.com',
        status: 'confirmed',
        paymentMethod: 'sbp',
        paymentStatus: 'paid',
        deliveryMethod: 'cdek_point',
        deliveryAddress: 'г. Санкт-Петербург, ПВЗ СДЭК',
        deliveryCost: 350,
        itemsTotal: 4980,
        totalAmount: 5330,
        items: [
            {
                id: 2,
                productId: 1,
                productName: 'Стринги на тонких лямках',
                articleNumber: 'BF2524830024',
                price: 990,
                quantity: 2,
                totalPrice: 1980,
            },
            {
                id: 3,
                productId: 2,
                productName: 'Бюстгальтер с пуш-ап',
                articleNumber: 'BF2524830025',
                price: 1500,
                quantity: 2,
                totalPrice: 3000,
            },
        ],
        createdAt: '2026-01-01',
        updatedAt: '2026-01-02',
    },
    {
        id: 3,
        orderNumber: 'BF2524830026',
        customerId: 3,
        customerName: 'Анна Сидорова',
        customerPhone: '+7 999 111-22-33',
        customerEmail: 'anna@email.com',
        status: 'processing',
        paymentMethod: 'cash_on_delivery',
        paymentStatus: 'unpaid',
        deliveryMethod: 'pickup_point',
        deliveryAddress: 'г. Казань, ПВЗ',
        deliveryCost: 0,
        itemsTotal: 19000,
        totalAmount: 19000,
        items: [],
        createdAt: '2026-01-01',
        updatedAt: '2026-01-03',
    },
    {
        id: 4,
        orderNumber: 'BF2524830027',
        customerId: 1,
        customerName: 'Ивана Иванова',
        customerPhone: '+7 999 123-45-67',
        customerEmail: 'ivana@email.com',
        status: 'delivered',
        paymentMethod: 'card',
        paymentStatus: 'paid',
        deliveryMethod: 'courier',
        deliveryAddress: 'г. Москва, ул. Примерная, д. 1, кв. 1',
        deliveryCost: 500,
        itemsTotal: 2990,
        totalAmount: 3490,
        items: [],
        createdAt: '2025-12-25',
        updatedAt: '2025-12-28',
    },
    {
        id: 5,
        orderNumber: 'BF2524830028',
        customerId: 4,
        customerName: 'Елена Козлова',
        customerPhone: '+7 999 444-55-66',
        customerEmail: 'elena@email.com',
        status: 'cancelled',
        paymentMethod: 'sbp',
        paymentStatus: 'refunded',
        deliveryMethod: 'cdek_point',
        deliveryAddress: 'г. Новосибирск, ПВЗ СДЭК',
        deliveryCost: 400,
        itemsTotal: 5990,
        totalAmount: 6390,
        items: [],
        createdAt: '2025-12-20',
        updatedAt: '2025-12-22',
    },
];
