export {Header} from './Header';
export {ActualInfo} from './ActualInfo';
export {MainPage} from './MainPage';
export {Card} from './Card';
export {Footer} from './Footer';
export {Layout} from './Layout';
export {NotFound} from './NotFound';
export {Catalog} from './Catalog';
export {Loader} from './Loader';