import type { Review } from './types';

export const mockReviews: Review[] = [
    {
        id: 1,
        productId: 1,
        productName: 'Стринги на тонких лямках',
        reviewText: 'Краткое отображение отзыва...',
        rating: 1,
        authorId: 1,
        authorName: 'Имя автора',
        date: '2026-01-01',
        status: 'moderation',
        hasPhoto: false,
    },
    {
        id: 2,
        productId: 2,
        productName: 'Бюстгальтер с пуш-ап',
        reviewText: 'Очень красивое белье, рекомендую!',
        rating: 5,
        authorId: 2,
        authorName: 'Мария',
        date: '2026-01-02',
        status: 'published',
        hasPhoto: true,
        photoUrls: ['https://placehold.co/100x100/f5f5f5/333?text=Photo'],
    },
    {
        id: 3,
        productId: 3,
        productName: 'Боди кружевное',
        reviewText: 'Хорошее качество, но размер маловат',
        rating: 4,
        authorId: 3,
        authorName: 'Анна',
        date: '2026-01-03',
        status: 'published',
        hasPhoto: false,
    },
    {
        id: 4,
        productId: 1,
        productName: 'Стринги на тонких лямках',
        reviewText: 'Не понравилось качество швов',
        rating: 2,
        authorId: 4,
        authorName: 'Елена',
        date: '2026-01-04',
        status: 'hidden',
        hasPhoto: false,
    },
    {
        id: 5,
        productId: 4,
        productName: 'Комплект "Нежность"',
        reviewText: 'Отличный комплект! Сидит идеально.',
        rating: 5,
        authorId: 5,
        authorName: 'Ольга',
        date: '2026-01-05',
        status: 'moderation',
        hasPhoto: true,
        photoUrls: ['https://placehold.co/100x100/f5f5f5/333?text=Photo1', 'https://placehold.co/100x100/f5f5f5/333?text=Photo2'],
    },
    {
        id: 6,
        productId: 2,
        productName: 'Бюстгальтер с пуш-ап',
        reviewText: 'Средненько...',
        rating: 3,
        authorId: 6,
        authorName: 'Светлана',
        date: '2026-01-06',
        status: 'moderation',
        hasPhoto: false,
    },
];
