import type { Promotion, PromoCode, LoyaltySettings } from './types';

export const mockPromotions: Promotion[] = [
    {
        id: 1,
        name: 'Весенняя распродажа',
        type: 'for_client',
        discountType: 'percent',
        discountValue: 20,
        minOrderAmount: 3990,
        scope: 'all_order',
        customerGroup: 'all',
        usageLimitTotal: 1300,
        usageLimitPerCustomer: 1,
        usedCount: 99,
        startDate: '2026-01-01',
        endDate: '2027-01-01',
        status: 'active',
    },
    {
        id: 2,
        name: 'Скидка для новых клиентов',
        type: 'for_client',
        discountType: 'percent',
        discountValue: 15,
        scope: 'all_order',
        customerGroup: 'new_only',
        usedCount: 45,
        startDate: '2026-01-01',
        endDate: '2027-01-01',
        status: 'active',
    },
    {
        id: 3,
        name: 'Подарок к заказу',
        type: 'internal',
        discountType: 'gift',
        discountValue: 0,
        minOrderAmount: 5000,
        scope: 'all_order',
        customerGroup: 'all',
        usedCount: 23,
        startDate: '2026-01-01',
        endDate: '2027-01-01',
        status: 'scheduled',
    },
    {
        id: 4,
        name: 'Фиксированная скидка 500₽',
        type: 'for_client',
        discountType: 'fixed_amount',
        discountValue: 500,
        minOrderAmount: 2000,
        scope: 'categories',
        customerGroup: 'all',
        usedCount: 156,
        startDate: '2025-12-01',
        endDate: '2025-12-31',
        status: 'completed',
    },
    {
        id: 5,
        name: 'Летняя акция',
        type: 'for_client',
        discountType: 'percent',
        discountValue: 10,
        scope: 'products',
        customerGroup: 'all',
        usedCount: 0,
        startDate: '2026-06-01',
        endDate: '2026-08-31',
        status: 'paused',
    },
];

export const mockPromoCodes: PromoCode[] = [
    {
        id: 1,
        code: 'SPRING20',
        promotionId: 1,
        promotionName: 'Весенняя распродажа',
        status: 'active',
        usedCount: 45,
    },
    {
        id: 2,
        code: 'WELCOME15',
        promotionId: 2,
        promotionName: 'Скидка для новых клиентов',
        status: 'active',
        usedCount: 30,
    },
    {
        id: 3,
        code: 'GIFT500',
        promotionId: 4,
        promotionName: 'Фиксированная скидка 500₽',
        status: 'inactive',
        usedCount: 100,
    },
];

export const mockLoyaltySettings: LoyaltySettings = {
    percentFromOrder: 5,
    minOrderAmount: 1000,
    pointsValidityDays: 365,
    pointsToRubleRate: 1,
};
